Feature/transaction page
gabito1451/minibankapp pull request #2
Opened 2023-03-27 07:23 UTC by gabito1451

Added Transaction and Deposit page 
The user is also directed to the transaction page if already logged in

2023-03-27 21:08 UTC, nwankwo-ikemefuna requested changes
Looks good 👍, but needs some changes.

2023-03-27 21:08 UTC, nwankwo-ikemefuna commented on .vscode/settings.json
> +{
Don't commit this file. It's specific to your workbench.

2023-03-27 21:08 UTC, nwankwo-ikemefuna commented on src/App.js
>          <Route path="/transaction" Component={Transaction} />
The last 2 should be protected routes. You should use a higher order component (HOC) which will wrap the protected route components. Research about how to do this.

Here is a suggestion by ChatGPT:

```
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';

// HOC for protecting routes
const ProtectedRoute = ({ component: Component, isLoggedIn, ...rest }) => {
  return (
    <Route
      {...rest}
      element={
        isLoggedIn ? (
          <Component />
        ) : (
          <Navigate to="/" replace />
        )
      }
    />
  );
};

// App component
const App = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  // your login/logout logic here

  return (
    <Router>
      <Routes>
        <Route path="/register" element={<Register />} />
        <Route path="/" element={<Login setIsLoggedIn={setIsLoggedIn} />} />
        <ProtectedRoute
          path="/transaction"
          element={<Transaction />}
          isLoggedIn={isLoggedIn}
        />
        <ProtectedRoute
          path="/deposit"
          element={<Deposit />}
          isLoggedIn={isLoggedIn}
        />
      </Routes>
    </Router>
  );
};
```

2023-03-27 21:08 UTC, nwankwo-ikemefuna commented on src/components/transaction.js
> +        onClick={() => clearTransactionHistory()}
This is a dangerous action, you should add confirm action.

2023-03-27 21:08 UTC, nwankwo-ikemefuna commented on src/components/transaction.js
> +              <tr>
Add key prop with transaction reference as value, as it's the only unique value of transaction.
`key={transaction.transactionReference}`

2023-03-27 21:08 UTC, nwankwo-ikemefuna commented on src/components/common-session-component/navbar.js
> +        <Link to="/logout" className="link">
There is no page called logout and there shouldn't be. You should attach an onClick function to the Link that will correctly log the user out and the redirect to login page.
Something like:
```
<Link className="link" onClick={handleLogout}>
     Log out
</Link>
```

2023-04-05 16:04 UTC, gabito1451 commented on .vscode/settings.json
> +{
Done

2023-04-05 16:04 UTC, gabito1451 commented on src/components/transaction.js
> +        onClick={() => clearTransactionHistory()}
Done

2023-04-05 16:04 UTC, gabito1451 commented on src/components/transaction.js
> +              <tr>
Done

2023-04-05 16:05 UTC, gabito1451 commented on src/components/common-session-component/navbar.js
> +        <Link to="/logout" className="link">
Done

2023-04-06 08:12 UTC, nwankwo-ikemefuna approved these changes

2023-04-06 08:17 UTC, merged